# -*- coding: utf-8 -*-
"""Engenheiros

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUUiypfnl_nwkdxi_dLwXmv6VA5zlVfz
"""

# O Cenário: Processando um JSON de Vendas (Os dados vêm como uma lista de dicionários.)

# Dados brutos (Ingestão)
vendas_brutas = [
    {"id": 1, "produto": "Mouse", "preco": 50.0, "qtd": 2},
    {"id": 2, "produto": "Teclado", "preco": 150.0, "qtd": 1},
    {"id": 3, "produto": "Monitor", "preco": 900.0, "qtd": 0}, # Venda inválida?
    {"id": 4, "produto": "Cadeira", "preco": 599.0, "qtd": 3},
    {"id": 3, "produto": "Monitor", "preco": 900.0, "qtd": 0}, # Venda inválida?
    {"id": 4, "produto": "Cadeira", "preco": 599.0, "qtd": 4 }
]

# Como engenheiro, sua primeira tarefa pode ser filtrar apenas vendas válidas (quantidade > 0).
# Para isso 1º Passo Transformação com Listas (Filtering)

# Usando "List Comprehension" para filtrar
vendas_validas = [item for item in vendas_brutas if item["qtd"] > 0]
print ( vendas_validas)

#Fazendo BASH comando linux, atuando como interface entre o usuário e o sistema operacional
# Principais comandos ls: Lista arquivos e pastas do diretório atual. cd: Navega entre diretórios.
# pwd: Exibe o diretório de trabalho atual. mv: Move ou renomeia arquivos/pastas.
# cp: Copia arquivos/pastas. rm: Remove arquivos/pastas. mkdir: Cria um novo diretório.
# grep: Pesquisa textos dentro de arquivos. echo: Exibe uma linha de texto.
# sudo: Executa comandos com privilégios de superusuário.

!git config --global user.name "Laura katiuscia"
!git config --global user.email "laura.katiusc@gmail.com"

!git clone https://github.com/laura-katiuscia/Projeto-Engenharia-de-dados.git

!mv Engenheiros.py
#

import os
from getpass import getpass

# 1. Configurações do Usuário
username = "https://github.com/laura-katiuscia" # Coloque seu usuário aqui
email = "laura.katiusc@gmail.com" # Coloque seu email aqui
repo_name = "Engenheiro de dados" # O nome exato do repositório
arquivo_para_subir = "Pedidos.csv" # O arquivo que você quer enviar

# 2. Solicita o Token de forma segura (cole o token gerado no passo 1 quando pedir)
password = getpass('Cole seu Personal Access Token aqui: ')

# 3. Configura o Git globalmente na máquina virtual
!git config --global user.email "$laura.katiusc@gmail.com"
!git config --global user.name "$Laura-Katiuscia"



vari = [item for item in vendas_brutas if item["qtd"] < 3]  # Fazer esse desafio
print(vari)  # Quantas vendas não são válidas

qtd_zeros = len([v for v in vendas_brutas if v['qtd'] == 0])
print(f"Método Curto: Foram encontradas {qtd_zeros} vendas com quantidade zero.")

# 2 Passo. Enriquecimento com Dicionários (Mapping)
# Agora, você precisa calcular o valor total de cada venda e adicionar essa nova informação.

for venda in vendas_validas:
    # Criando uma nova chave no dicionário (Enriquecimento)
    venda["total_faturado"] = venda["preco"] * venda["qtd"]

    # Removendo dados sensíveis ou desnecessários
    venda.pop("id", None) # Usamos .pop() para evitar KeyError se 'id' já tiver sido removido
    print(venda)

    # Dicionários: São perfeitos para linha de uma tabela, Listas: Registros processamos lotes (batches
    # Na vida real, quando o volume cresce, o engenheiro de dados converte essa lista de dicionários em um DataFrame (Pandas ou PySpark).

# mágica da Engenharia de Dados acontece: sai de um formato flexível (JSON/Dicionários)
# para um formato de alta performance (Tabelas/DataFrames).
# Pandas é a biblioteca que faz essa ponte. Ele pega sua lista de dicionários e a organiza em colunas,
# permitindo que você trate os dados como
# se estivesse em um SQL ou Excel potente.

# De Dicionários para DataFrame
import pandas as pd

# 1. Nossa lista de dicionários (os dados que vieram da API)
dados_vendas = [
    {"produto": "Mouse", "preco": 50.0, "qtd": 2},
    {"produto": "Teclado", "preco": 150.0, "qtd": 1},
    {"produto": "Monitor", "preco": 900.0, "qtd": 5},
    {"produto": "Monitor", "preco": 900.0, "qtd": 3},
    {"produto": "Monitor", "preco": 900.0, "qtd": 10}
]

# 2. Transformando para DataFrame (Tabela)
df = pd.DataFrame(dados_vendas)

# 3. Criando uma nova coluna de forma performática (estilo Vetor/Matriz)
df['total'] = df['preco'] * df['qtd']
df['teste'] = df['preco'] - df['qtd']

print(df)

# Desafio aceito! Na vida real, os dados de engenharia raramente vêm "limpinhos".
# Muitas vezes, eles vêm em dicionários aninhados (um dicionário dentro de outro, dentro de uma lista).

# Imagine que você recebeu os dados de um sensor de temperatura de uma fábrica. O formato é este:
dados_sensor = {
    "fabrica": "Unidade Sul",  "sensores": [
        {"id": "S1", "leitura": {"valor": 25.5, "unidade": "C"}},
        {"id": "S2", "leitura": {"valor": 30.2, "unidade": "C"}},
        {"id": "S3", "leitura": {"valor": 22.8, "unidade": "C"}},
        {"id": "S4", "leitura": {"valor": 29.5, "unidade": "C"}},
        {"id": "S5", "leitura": {"valor": 32.2, "unidade": "C"}},
        {"id": "S6", "leitura": {"valor": 22.10, "unidade": "C"}}
    ]
}
print(dados_sensor)

# Para acessar e imprimir o valor da leitura (30.2) do segundo sensor (S2),
# conforme o desafio em '0kKoQvgfP0sq', navegue o dicionário 'dados_sensor'.

# O seu objetivo: Como você faria para acessar e imprimir apenas o valor da leitura (o número 30.2) do segundo sensor (S2)?
# Dica de Engenheiro: 1. Primeiro, acesse a chave "sensores". 2. Lembre-se que o

# que está dentro de "sensores" é uma lista (use colchetes [] e o índice começando em 0).
#  3. Depois, vá entrando nas chaves do dicionário interno. Como ficaria o seu código para chegar nesse 30.2?

# Quando você conseguir acessar esse valor, terá dominado a lógica fundamental de como os dados trafegam na internet.
# Dica final antes de ir: No Python, você vai "empilhando" os acessos, algo como: dados_sensor['chave'][indice]['outra_chave']...

valor_sensor_s2 = dados_sensor['sensores'][1]['leitura']['valor'] # Anatomia do seu Acesso
print(f"O valor da leitura do segundo sensor (S2) é: {valor_sensor_s2}")  # ['sensores']: Acessa a lista principal de sensores.

                                                                  # 1 é posição e ['leitura']: Entra no dicionário de dados daquele sensor específico.
                                                                  # ['valor']: Captura finalmente o dado numérico que você buscava.

# O dicionário de exemplo
dados_sensor = {
    "sensores": [
        {"id": "S1", "leitura": {"valor": 25.5}},
        {"id": "S2", "leitura": {"valor": 30.2}},
        {"id": "S3", "leitura": {"valor": 18.9}}
    ]
}

# Buscando o sensor pelo ID de forma segura
valor_encontrado = None

for sensor in dados_sensor['sensores']:
    if sensor['id'] == 'S2':
        valor_encontrado = sensor['leitura']['valor']
        break  # Encontrou? Para de procurar para poupar processamento!

if valor_encontrado is not None:
    print(f"Sucesso! O valor do S2 é: {valor_encontrado}")
else:
    print("Sensor não encontrado.")

import pandas as pa

novo = pa.read_csv('Pedidos.csv', sep=';')
print(novo)

#Primeiras linhas

novo.head()

#Linhas aleatórias (Cada clique ele mostra uma linha aleatória)

novo.sample()

## Ver registros mais recentes (ex: últimos dias de vendas)
# E identiica se tiver valores estranhos no final do dataset
# conferir se nada quebrou no final do dataset 😉

novo.tail()

#Quantidade de linhas e colunas que tem dataset

novo.shape

#Vê se tem alguma linha duplicada com linha idêntica a outra em TODAS as colunas
novo.duplicated().sum()

#🔍 Como ver essa linha duplicada

novo[novo.duplicated()] # aqui mostra somente linha 1 e duplicada de 0, já linha de comando abaixo mostra as 2 linhas
novo[novo.duplicated(keep=False)]

#🧹 Como remover duplicatas (se fizer sentido)

novo = novo.drop_duplicates()

novo.head()

# análise exploratória de dados 👀📊 resumo estatístico completo
# 🔤 Para colunas categóricas (texto) Você verá:

# count → valores não nulos (Ver se existem categorias repetidas demais
# Encontrar valores fora do esperado, Ter uma visão geral antes de modelar)

# unique → quantos valores diferentes
# top → valor mais frequente
# freq → quantas vezes ele aparece

novo.describe(include='all')

# 💡 Resumo: groupby = “separa os dados em grupos e calcula algo para cada grupo”
# Esse atividade não usei devido não ter necessidade de calculos, mas uso select

novo[['Data Pedido','Prioridade Pedido']]

# Usando SELECT COM WHERE
novo[novo['Prioridade Pedido'] == 'Critico']

#
novo['Prioridade Pedido'].value_counts()

# Ideal para análise exploratória (EDA).
import matplotlib.pyplot as plt

# Padroniza os textos (boa prática)
prioridades = (
    novo['Prioridade Pedido']
    .str.strip()
    .str.capitalize()
)

# Conta quantos pedidos por prioridade
contagem = prioridades.value_counts()

# Cria o gráfico
contagem.plot(kind='bar')

plt.title('Distribuição de Prioridade dos Pedidos')
plt.xlabel('Prioridade do Pedido')
plt.ylabel('Quantidade de Pedidos')

plt.show()